apiVersion: numaflow.numaproj.io/v1alpha1
kind: MonoVertex
metadata:
  name: http-source
spec:
  source:
    udsource:
      container:
        env:
          - name: HTTP_SOURCE_PORT
            value: "8080"
        image: quay.io/numaio/numaflow-rs/http-source:stable
        imagePullPolicy: IfNotPresent
  sink:
    log: {}