[package]
name = "source-transformer-event-time-filter"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
numaflow = { git = "https://github.com/numaproj/numaflow-rs.git", branch="main" }
tokio = "1.38.0"
chrono = "0.4.38"
tonic = "0.11.0"