[package]
name = "map-tracing"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tonic.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
numaflow = { path = "../../numaflow" }

opentelemetry = "0.31"
opentelemetry_sdk = { version = "0.31", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.31", features = ["grpc-tonic"] }
tracing-opentelemetry = "0.32"
