[package]
name = "sink-log"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
tonic.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
numaflow = { path = "../../numaflow" }
