apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: sliding-sorter
spec:
  edges:
  - from: in
    to: accum
  - from: accum
    to: sink
  vertices:
  - name: in
    scale:
      min: 1
    source:
      udsource:
        container:
          env:
          - name: NUM_KEYS
            value: "10"
          - name: FLUSH_INTERVAL_SECS
            value: "60"
          - name: EMIT_INTERVAL_MS
            value: "100"
          - name: MAX_TPS
            value: "0"
          image: docker.intuit.com/personal/vtiwari5/numaflow-rs/sliding-keys-source:stable
          imagePullPolicy: Always
  - name: accum
    udf:
      container:
        env:
        - name: MALLOC_ARENA_MAX
          value: "2"
        - name: MALLOC_TRIM_THRESHOLD_
          value: "131072"
        image: docker.intuit.com/personal/vtiwari5/numaflow-rs/stream-sorter:stable
      groupBy:
        keyed: true
        storage:
          persistentVolumeClaim:
            volumeSize: 1Gi
        window:
          accumulator:
            timeout: 5s
  - name: sink
    scale:
      min: 1
    sink:
      log: {}
