apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: sliding-sorter
spec:
  edges:
  - from: in
    to: accum
  - from: accum
    to: sink
  vertices:
  - name: in
    scale:
      min: 1
    source:
      udsource:
        container:
          env:
          - name: NUM_KEYS
            value: "10"
          - name: FLUSH_INTERVAL_SECS
            value: "60"
          - name: EMIT_INTERVAL_MS
            value: "100"
          - name: MAX_TPS
            value: "100"
          image: docker.intuit.com/personal/vtiwari5/numaflow-rs/sliding-keys-source:stable
          imagePullPolicy: Always
  - name: accum
    containerTemplate:
      env:
        - { name: LD_PRELOAD, value: /usr/share/libbytehound.so }
        - { name: MEMORY_PROFILER_LOG, value: info }
        - { name: MEMORY_PROFILER_OUTPUT, value: /var/numaflow/pbq/memory-profiling_%e_%t_%p.dat }
        - { name: MEMORY_PROFILER_CULL_TEMPORARY_ALLOCATIONS, value: "1" }
        - { name: MEMORY_PROFILER_GRAB_BACKTRACES_ON_FREE, value: "0" }
      securityContext:
        capabilities:
          add:
            - SYS_PTRACE
    udf:
      container:
        env:
        image: docker.intuit.com/personal/vtiwari5/numaflow-rs/stream-sorter:stable
      groupBy:
        keyed: true
        storage:
          persistentVolumeClaim:
            volumeSize: 1Gi
        window:
          accumulator:
            timeout: 5s
  - name: sink
    scale:
      min: 1
    sink:
      log: {}
