apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: kafka-pl
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-rs/simple-source:v1
            imagePullPolicy: Always
        transformer:
          container:
            # Filter messages based on event time, see https://github.com/numaproj/numaflow-go/tree/main/pkg/sourcetransformer/examples/event_time_filter
            image: quay.io/numaio/numaflow-rust/source-transformer:stable
            imagePullPolicy: Always
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: out