apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-source
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-rs/simple-source:stable
            imagePullPolicy: Always
    - name: out
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: out